onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_uart/break_count
add wave -noupdate /tb_uart/frame_count
add wave -noupdate /tb_uart/parity_count
add wave -noupdate /tb_uart/addr_in
add wave -noupdate /tb_uart/addr_out
add wave -noupdate /tb_uart/baud_clock
add wave -noupdate /tb_uart/baud_diff
add wave -noupdate /tb_uart/baud_loop
add wave -noupdate /tb_uart/baud_measure
add wave -noupdate /tb_uart/baud_percent
add wave -noupdate /tb_uart/clk_set
add wave -noupdate /tb_uart/cpu_addr
add wave -noupdate /tb_uart/cpu_csn
add wave -noupdate /tb_uart/cpu_din
add wave -noupdate -expand /tb_uart/cpu_dout
add wave -noupdate /tb_uart/cpu_int
add wave -noupdate /tb_uart/cpu_rdwrn
add wave -noupdate /tb_uart/cpu_valid
add wave -noupdate /tb_uart/data_reg
add wave -noupdate /tb_uart/data_shift
add wave -noupdate /tb_uart/enable_uart1_rx
add wave -noupdate /tb_uart/exp_baud
add wave -noupdate /tb_uart/ext_loopback
add wave -noupdate /tb_uart/i
add wave -noupdate /tb_uart/j
add wave -noupdate /tb_uart/k
add wave -noupdate /tb_uart/rtsn_start
add wave -noupdate /tb_uart/rtsn_stop
add wave -noupdate /tb_uart/send_data
add wave -noupdate /tb_uart/stop_on_fail
add wave -noupdate /tb_uart/sys_clk
add wave -noupdate /tb_uart/sys_rstn
add wave -noupdate /tb_uart/test_failed
add wave -noupdate /tb_uart/test_reg
add wave -noupdate /tb_uart/time_diff
add wave -noupdate /tb_uart/uart_ctsn
add wave -noupdate /tb_uart/uart_ctsn_1
add wave -noupdate /tb_uart/uart_rtsn
add wave -noupdate /tb_uart/uart_rtsn_1
add wave -noupdate /tb_uart/uart_rx
add wave -noupdate /tb_uart/uart_rx_1
add wave -noupdate /tb_uart/uart_tx
add wave -noupdate /tb_uart/uart_tx_1
add wave -noupdate -divider uart
add wave -noupdate /tb_uart/u_uart1/autoflow
add wave -noupdate /tb_uart/u_uart1/baud_terminal_count
add wave -noupdate /tb_uart/u_uart1/cpu_addr
add wave -noupdate /tb_uart/u_uart1/cpu_csn
add wave -noupdate /tb_uart/u_uart1/cpu_din
add wave -noupdate /tb_uart/u_uart1/cpu_dout
add wave -noupdate /tb_uart/u_uart1/cpu_rdwrn
add wave -noupdate /tb_uart/u_uart1/cpu_ready
add wave -noupdate /tb_uart/u_uart1/cpu_valid
add wave -noupdate /tb_uart/u_uart1/din_shift
add wave -noupdate /tb_uart/u_uart1/cpu_int
add wave -noupdate /tb_uart/u_uart1/enable_tx
add wave -noupdate /tb_uart/u_uart1/tx_data_avail
add wave -noupdate /tb_uart/u_uart1/tx_fifo_pop
add wave -noupdate /tb_uart/u_uart1/tx_shift_empty
add wave -noupdate /tb_uart/u_uart1/uart_tx
add wave -noupdate /tb_uart/u_uart1/force_rts
add wave -noupdate /tb_uart/u_uart1/int_rx
add wave -noupdate /tb_uart/u_uart1/loopback
add wave -noupdate /tb_uart/u_uart1/tx_fifo_dout
add wave -noupdate /tb_uart/u_uart1/parity
add wave -noupdate /tb_uart/u_uart1/rx_clk_cnt
add wave -noupdate /tb_uart/u_uart1/rx_data_cnt
add wave -noupdate /tb_uart/u_uart1/rx_data_shift
add wave -noupdate /tb_uart/u_uart1/rx_fifo_din
add wave -noupdate /tb_uart/u_uart1/rx_fifo_full
add wave -noupdate /tb_uart/u_uart1/rx_fifo_push
add wave -noupdate /tb_uart/u_uart1/rx_frame_err
add wave -noupdate /tb_uart/u_uart1/rx_parity_err
add wave -noupdate /tb_uart/u_uart1/rx_shift
add wave -noupdate /tb_uart/u_uart1/rx_sm
add wave -noupdate /tb_uart/u_uart1/sys_clk
add wave -noupdate /tb_uart/u_uart1/sys_rstn
add wave -noupdate /tb_uart/u_uart1/tx_clk_cnt
add wave -noupdate /tb_uart/u_uart1/tx_ctsn
add wave -noupdate /tb_uart/u_uart1/tx_data_cnt
add wave -noupdate /tb_uart/u_uart1/tx_rtsn
add wave -noupdate /tb_uart/u_uart1/tx_shift
add wave -noupdate /tb_uart/u_uart1/tx_sm
add wave -noupdate /tb_uart/u_uart1/uart_ctsn
add wave -noupdate /tb_uart/u_uart1/uart_rtsn
add wave -noupdate /tb_uart/u_uart1/uart_rx
add wave -noupdate /tb_uart/u_uart1/uart_rxd
add wave -noupdate /tb_uart/u_uart1/vote_bit
add wave -noupdate -divider CPU
add wave -noupdate /tb_uart/u_uart1/u_cpu/sys_clk
add wave -noupdate /tb_uart/u_uart1/u_cpu/sys_rstn
add wave -noupdate /tb_uart/u_uart1/u_cpu/baud_en
add wave -noupdate /tb_uart/u_uart1/u_cpu/cpu_rdwrn
add wave -noupdate /tb_uart/u_uart1/u_cpu/cpu_csn
add wave -noupdate /tb_uart/u_uart1/u_cpu/dlab
add wave -noupdate /tb_uart/u_uart1/u_cpu/cpu_addr
add wave -noupdate /tb_uart/u_uart1/u_cpu/cpu_din
add wave -noupdate /tb_uart/u_uart1/u_cpu/cpu_dout
add wave -noupdate /tb_uart/u_uart1/u_cpu/cpu_ready
add wave -noupdate /tb_uart/u_uart1/u_cpu/cpu_valid
add wave -noupdate /tb_uart/u_uart1/u_cpu/cpu_int
add wave -noupdate /tb_uart/u_uart1/u_cpu/baud_terminal_count
add wave -noupdate /tb_uart/u_uart1/u_cpu/parity
add wave -noupdate /tb_uart/u_uart1/u_cpu/force_rts
add wave -noupdate /tb_uart/u_uart1/u_cpu/autoflow
add wave -noupdate /tb_uart/u_uart1/u_cpu/loopback
add wave -noupdate /tb_uart/u_uart1/u_cpu/rx_fifo_push
add wave -noupdate /tb_uart/u_uart1/u_cpu/rx_fifo_din
add wave -noupdate /tb_uart/u_uart1/u_cpu/rx_parity_err
add wave -noupdate /tb_uart/u_uart1/u_cpu/rx_frame_err
add wave -noupdate /tb_uart/u_uart1/u_cpu/rx_fifo_full
add wave -noupdate /tb_uart/u_uart1/u_cpu/tx_fifo_pop
add wave -noupdate /tb_uart/u_uart1/u_cpu/tx_shift_empty
add wave -noupdate /tb_uart/u_uart1/u_cpu/tx_data_avail
add wave -noupdate /tb_uart/u_uart1/u_cpu/tx_fifo_dout
add wave -noupdate /tb_uart/u_uart1/u_cpu/uart_cts
add wave -noupdate /tb_uart/u_uart1/u_cpu/break_en
add wave -noupdate /tb_uart/u_uart1/u_cpu/fifo_enable
add wave -noupdate /tb_uart/u_uart1/u_cpu/reset_rx_fifo
add wave -noupdate /tb_uart/u_uart1/u_cpu/reset_tx_fifo
add wave -noupdate /tb_uart/u_uart1/u_cpu/scratch_reg
add wave -noupdate /tb_uart/u_uart1/u_cpu/cts_change
add wave -noupdate /tb_uart/u_uart1/u_cpu/cts_last
add wave -noupdate /tb_uart/u_uart1/u_cpu/rx_fifo_out
add wave -noupdate /tb_uart/u_uart1/u_cpu/rx_fifo_pop
add wave -noupdate /tb_uart/u_uart1/u_cpu/rx_fifo_empty
add wave -noupdate /tb_uart/u_uart1/u_cpu/rx_data_avail
add wave -noupdate /tb_uart/u_uart1/u_cpu/rx_fifo_count
add wave -noupdate /tb_uart/u_uart1/u_cpu/rx_thresh
add wave -noupdate /tb_uart/u_uart1/u_cpu/rx_toggle
add wave -noupdate /tb_uart/u_uart1/u_cpu/tx_toggle
add wave -noupdate /tb_uart/u_uart1/u_cpu/en_rx_data_avail
add wave -noupdate /tb_uart/u_uart1/u_cpu/en_tx_fifo_empty
add wave -noupdate /tb_uart/u_uart1/u_cpu/en_rx_status_change
add wave -noupdate /tb_uart/u_uart1/u_cpu/en_msr_change
add wave -noupdate /tb_uart/u_uart1/u_cpu/tx_fifo_empty
add wave -noupdate /tb_uart/u_uart1/u_cpu/rx_status_change
add wave -noupdate /tb_uart/u_uart1/u_cpu/msr_change
add wave -noupdate /tb_uart/u_uart1/u_cpu/thr_empty
add wave -noupdate /tb_uart/u_uart1/u_cpu/int_status
add wave -noupdate /tb_uart/u_uart1/u_cpu/char_timeout
add wave -noupdate /tb_uart/u_uart1/u_cpu/frame_err
add wave -noupdate /tb_uart/u_uart1/u_cpu/tx_fifo_push
add wave -noupdate /tb_uart/u_uart1/u_cpu/tx_fifo_din
add wave -noupdate /tb_uart/u_uart1/u_cpu/overrun_error
add wave -noupdate /tb_uart/u_uart1/u_cpu/parity_err
add wave -noupdate /tb_uart/u_uart1/u_cpu/rx_fifo_error
add wave -noupdate /tb_uart/u_uart1/u_cpu/cpu_state
add wave -noupdate /tb_uart/u_uart1/u_cpu/rx_break_det
add wave -noupdate /tb_uart/u_uart1/u_cpu/break_det
add wave -noupdate /tb_uart/u_uart1/u_cpu/tx_fifo_full
add wave -noupdate -divider TX_FIFO
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_tx/DWIDTH
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_tx/addr_in
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_tx/addr_out
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_tx/af
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_tx/data_avail
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_tx/data_thresh
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_tx/fifo_count
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_tx/fifo_din
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_tx/fifo_empty
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_tx/fifo_full
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_tx/fifo_out
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_tx/fifo_pop
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_tx/fifo_push
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_tx/fifo_store
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_tx/last_af
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_tx/reset_fifo
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_tx/sys_clk
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_tx/sys_rstn
add wave -noupdate -divider RX_FIFO
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_rx/DWIDTH
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_rx/addr_in
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_rx/addr_out
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_rx/af
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_rx/data_avail
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_rx/data_thresh
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_rx/fifo_count
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_rx/fifo_din
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_rx/fifo_empty
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_rx/fifo_full
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_rx/fifo_out
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_rx/fifo_pop
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_rx/fifo_push
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_rx/fifo_store
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_rx/last_af
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_rx/reset_fifo
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_rx/sys_clk
add wave -noupdate /tb_uart/u_uart1/u_cpu/u_rx/sys_rstn
add wave -noupdate -divider UARTRX
add wave -noupdate /tb_uart/u_uart2/cpu_int
add wave -noupdate /tb_uart/u_uart2/int_rx
add wave -noupdate /tb_uart/u_uart2/rx_baud_reset
add wave -noupdate /tb_uart/u_uart2/rx_baudclk_en
add wave -noupdate /tb_uart/u_uart2/rx_fifo_din
add wave -noupdate /tb_uart/u_uart2/rx_fifo_full
add wave -noupdate /tb_uart/u_uart2/rx_fifo_push
add wave -noupdate /tb_uart/u_uart2/rx_frame_err
add wave -noupdate /tb_uart/u_uart2/rx_parity_err
add wave -noupdate /tb_uart/u_uart2/rx_shift
add wave -noupdate /tb_uart/u_uart2/rx_sm
add wave -noupdate /tb_uart/u_uart2/autoflow
add wave -noupdate /tb_uart/u_uart2/baud_reset
add wave -noupdate /tb_uart/u_uart2/baud_terminal_count
add wave -noupdate /tb_uart/u_uart2/cpu_addr
add wave -noupdate /tb_uart/u_uart2/cpu_csn
add wave -noupdate /tb_uart/u_uart2/cpu_din
add wave -noupdate /tb_uart/u_uart2/cpu_dout
add wave -noupdate /tb_uart/u_uart2/cpu_rdwrn
add wave -noupdate /tb_uart/u_uart2/cpu_ready
add wave -noupdate /tb_uart/u_uart2/cpu_valid
add wave -noupdate /tb_uart/u_uart2/din_shift
add wave -noupdate /tb_uart/u_uart2/enable_tx
add wave -noupdate /tb_uart/u_uart2/force_rts
add wave -noupdate /tb_uart/u_uart2/loopback
add wave -noupdate /tb_uart/u_uart2/parity
add wave -noupdate /tb_uart/u_uart2/rx_clk_cnt
add wave -noupdate /tb_uart/u_uart2/rx_clken_count
add wave -noupdate /tb_uart/u_uart2/rx_data_cnt
add wave -noupdate /tb_uart/u_uart2/rx_data_shift
add wave -noupdate /tb_uart/u_uart2/sys_clk
add wave -noupdate /tb_uart/u_uart2/sys_rstn
add wave -noupdate /tb_uart/u_uart2/tx_baudclk_en
add wave -noupdate /tb_uart/u_uart2/tx_clk_cnt
add wave -noupdate /tb_uart/u_uart2/tx_clken_count
add wave -noupdate /tb_uart/u_uart2/tx_ctsn
add wave -noupdate /tb_uart/u_uart2/tx_data_avail
add wave -noupdate /tb_uart/u_uart2/tx_data_cnt
add wave -noupdate /tb_uart/u_uart2/tx_fifo_dout
add wave -noupdate /tb_uart/u_uart2/tx_fifo_pop
add wave -noupdate /tb_uart/u_uart2/tx_rtsn
add wave -noupdate /tb_uart/u_uart2/tx_shift
add wave -noupdate /tb_uart/u_uart2/tx_shift_empty
add wave -noupdate /tb_uart/u_uart2/tx_sm
add wave -noupdate /tb_uart/u_uart2/uart_ctsn
add wave -noupdate /tb_uart/u_uart2/uart_rtsn
add wave -noupdate /tb_uart/u_uart2/uart_rx
add wave -noupdate /tb_uart/u_uart2/uart_rxd
add wave -noupdate /tb_uart/u_uart2/uart_tx
add wave -noupdate /tb_uart/u_uart2/vote_bit
add wave -noupdate /tb_uart/u_uart2/voted
add wave -noupdate -divider RX_CPU
add wave -noupdate /tb_uart/u_uart2/u_cpu/autoflow
add wave -noupdate /tb_uart/u_uart2/u_cpu/baud_en
add wave -noupdate /tb_uart/u_uart2/u_cpu/baud_reset
add wave -noupdate /tb_uart/u_uart2/u_cpu/baud_terminal_count
add wave -noupdate /tb_uart/u_uart2/u_cpu/break_det
add wave -noupdate /tb_uart/u_uart2/u_cpu/break_en
add wave -noupdate /tb_uart/u_uart2/u_cpu/char_timeout
add wave -noupdate /tb_uart/u_uart2/u_cpu/cpu_addr
add wave -noupdate /tb_uart/u_uart2/u_cpu/cpu_csn
add wave -noupdate /tb_uart/u_uart2/u_cpu/cpu_din
add wave -noupdate /tb_uart/u_uart2/u_cpu/cpu_dout
add wave -noupdate /tb_uart/u_uart2/u_cpu/cpu_int
add wave -noupdate /tb_uart/u_uart2/u_cpu/cpu_rdwrn
add wave -noupdate /tb_uart/u_uart2/u_cpu/cpu_ready
add wave -noupdate /tb_uart/u_uart2/u_cpu/cpu_state
add wave -noupdate /tb_uart/u_uart2/u_cpu/cpu_valid
add wave -noupdate /tb_uart/u_uart2/u_cpu/cts_change
add wave -noupdate /tb_uart/u_uart2/u_cpu/cts_last
add wave -noupdate /tb_uart/u_uart2/u_cpu/dlab
add wave -noupdate /tb_uart/u_uart2/u_cpu/en_msr_change
add wave -noupdate /tb_uart/u_uart2/u_cpu/en_rx_data_avail
add wave -noupdate /tb_uart/u_uart2/u_cpu/en_rx_status_change
add wave -noupdate /tb_uart/u_uart2/u_cpu/en_tx_fifo_empty
add wave -noupdate /tb_uart/u_uart2/u_cpu/fifo_enable
add wave -noupdate /tb_uart/u_uart2/u_cpu/force_rts
add wave -noupdate /tb_uart/u_uart2/u_cpu/frame_err
add wave -noupdate /tb_uart/u_uart2/u_cpu/int_status
add wave -noupdate /tb_uart/u_uart2/u_cpu/loopback
add wave -noupdate /tb_uart/u_uart2/u_cpu/msr_change
add wave -noupdate /tb_uart/u_uart2/u_cpu/overrun_error
add wave -noupdate /tb_uart/u_uart2/u_cpu/parity
add wave -noupdate /tb_uart/u_uart2/u_cpu/parity_err
add wave -noupdate /tb_uart/u_uart2/u_cpu/reset_rx_fifo
add wave -noupdate /tb_uart/u_uart2/u_cpu/reset_tx_fifo
add wave -noupdate /tb_uart/u_uart2/u_cpu/rx_break_det
add wave -noupdate /tb_uart/u_uart2/u_cpu/rx_data_avail
add wave -noupdate /tb_uart/u_uart2/u_cpu/rx_fifo_count
add wave -noupdate /tb_uart/u_uart2/u_cpu/rx_fifo_din
add wave -noupdate /tb_uart/u_uart2/u_cpu/rx_fifo_empty
add wave -noupdate /tb_uart/u_uart2/u_cpu/rx_fifo_error
add wave -noupdate /tb_uart/u_uart2/u_cpu/rx_fifo_full
add wave -noupdate /tb_uart/u_uart2/u_cpu/rx_fifo_out
add wave -noupdate /tb_uart/u_uart2/u_cpu/rx_fifo_pop
add wave -noupdate /tb_uart/u_uart2/u_cpu/rx_fifo_push
add wave -noupdate /tb_uart/u_uart2/u_cpu/rx_frame_err
add wave -noupdate /tb_uart/u_uart2/u_cpu/rx_parity_err
add wave -noupdate /tb_uart/u_uart2/u_cpu/rx_status_change
add wave -noupdate /tb_uart/u_uart2/u_cpu/rx_thresh
add wave -noupdate /tb_uart/u_uart2/u_cpu/rx_toggle
add wave -noupdate /tb_uart/u_uart2/u_cpu/scratch_reg
add wave -noupdate /tb_uart/u_uart2/u_cpu/sys_clk
add wave -noupdate /tb_uart/u_uart2/u_cpu/sys_rstn
add wave -noupdate /tb_uart/u_uart2/u_cpu/thr_empty
add wave -noupdate /tb_uart/u_uart2/u_cpu/tx_data_avail
add wave -noupdate /tb_uart/u_uart2/u_cpu/tx_fifo_din
add wave -noupdate /tb_uart/u_uart2/u_cpu/tx_fifo_dout
add wave -noupdate /tb_uart/u_uart2/u_cpu/tx_fifo_empty
add wave -noupdate /tb_uart/u_uart2/u_cpu/tx_fifo_full
add wave -noupdate /tb_uart/u_uart2/u_cpu/tx_fifo_pop
add wave -noupdate /tb_uart/u_uart2/u_cpu/tx_fifo_push
add wave -noupdate /tb_uart/u_uart2/u_cpu/tx_shift_empty
add wave -noupdate /tb_uart/u_uart2/u_cpu/tx_shift_empty_d
add wave -noupdate /tb_uart/u_uart2/u_cpu/tx_toggle
add wave -noupdate /tb_uart/u_uart2/u_cpu/uart_cts
add wave -noupdate -divider RX_FIFO
add wave -noupdate /tb_uart/u_uart2/u_cpu/u_rx/addr_in
add wave -noupdate /tb_uart/u_uart2/u_cpu/u_rx/addr_out
add wave -noupdate /tb_uart/u_uart2/u_cpu/u_rx/af
add wave -noupdate /tb_uart/u_uart2/u_cpu/u_rx/data_avail
add wave -noupdate /tb_uart/u_uart2/u_cpu/u_rx/data_thresh
add wave -noupdate /tb_uart/u_uart2/u_cpu/u_rx/fifo_count
add wave -noupdate /tb_uart/u_uart2/u_cpu/u_rx/fifo_din
add wave -noupdate /tb_uart/u_uart2/u_cpu/u_rx/fifo_empty
add wave -noupdate /tb_uart/u_uart2/u_cpu/u_rx/fifo_full
add wave -noupdate /tb_uart/u_uart2/u_cpu/u_rx/fifo_out
add wave -noupdate /tb_uart/u_uart2/u_cpu/u_rx/fifo_pop
add wave -noupdate /tb_uart/u_uart2/u_cpu/u_rx/fifo_push
add wave -noupdate /tb_uart/u_uart2/u_cpu/u_rx/fifo_store
add wave -noupdate /tb_uart/u_uart2/u_cpu/u_rx/last_af
add wave -noupdate /tb_uart/u_uart2/u_cpu/u_rx/reset_fifo
add wave -noupdate /tb_uart/u_uart2/u_cpu/u_rx/sys_clk
add wave -noupdate /tb_uart/u_uart2/u_cpu/u_rx/sys_rstn
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {278205760 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 226
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {271243270 ps} {289081320 ps}
