# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg484-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/fbruno/projects/spacex/uart/vivado/uart/uart.cache/wt [current_project]
set_property parent.project_path /home/fbruno/projects/spacex/uart/vivado/uart/uart.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.2 [current_project]
read_verilog -library xil_defaultlib {
  /home/fbruno/projects/spacex/uart/rtl/sync_fifo.v
  /home/fbruno/projects/spacex/uart/rtl/uart_cpu.v
  /home/fbruno/projects/spacex/uart/rtl/uart.v
}
catch { write_hwdef -file uart.hwdef }
synth_design -top uart -part xc7z020clg484-1
write_checkpoint -noxdef uart.dcp
catch { report_utilization -file uart_utilization_synth.rpt -pb uart_utilization_synth.pb }
